# If want to input None, use !!null
sock_data: 5001

batch_size: 256 # def: 256

# Directories
train_folder: /root/jinhou/DL_dataset/ilsvrc12/parsed_data/train_hkl_b256_b256_bchw/
val_folder: /root/jinhou/DL_dataset/ilsvrc12/parsed_data/val_hkl_b256_b256_bchw/
